=== FFrein/Univer-BSTU/sem4/Java ТПвИ Технологии программирования в интернете/LR4/LR3/src/main/LibraryValidator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="PaperMediaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Book"></xs:enumeration>
            <xs:enumeration value="Jrnl"></xs:enumeration>
            <xs:enumeration value="Nwsp"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Seller"></xs:element>
                <xs:element name="ARRAY_PM" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PaperMedia" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="YearPublic"/>
                                        <xs:element type="xs:string" name="Pages"/>
                                        <xs:element type="xs:string" name="Price"/>
                                        <xs:element type="xs:string" name="Author"/>
                                        <xs:element type="PaperMediaType" name="PMT"/>
                                        <xs:element type="xs:string" name="Name"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FFrein/Univer-BSTU/sem4/Java ТПвИ Технологии программирования в интернете/LR4/LR3/src/main/Library.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="LibraryValidator.xsd">
    <Seller>Sel1</Seller>
    <ARRAY_PM>
        <PaperMedia>
            <YearPublic>2000</YearPublic>
            <Pages>386</Pages>
            <Price>220</Price>
            <Author>Pee</Author>
            <PMT>Jrnl</PMT>
            <Name>Fight Club</Name>
        </PaperMedia>
        <PaperMedia>
            <YearPublic>1998</YearPublic>
            <Pages>386</Pages>
            <Price>120</Price>
            <Author>Pee</Author>
            <PMT>Book</PMT>
            <Name>1998</Name>
        </PaperMedia>
        <PaperMedia>
            <YearPublic>2023</YearPublic>
            <Pages>13</Pages>
            <Price>12</Price>
            <Author>Nwsp</Author>
            <PMT>Book</PMT>
            <Name>Red News</Name>
        </PaperMedia>
    </ARRAY_PM>
</Library>
